# Number of days of inactivity before an issue becomes stale
daysUntilStale: 15
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - "[-_-] In Process"
  - ">_< Working & Scheduled"
# Label to use when marking an issue as stale
staleLabel: ">_< Wontfix"
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  This issue has now been automatically closed because of complete inactivity. Feel free to comment otu below to keep it open. Thank you
  for your contributions.
